### ISSUE TITLE
Container with host mounted volume serving corrupt files

### ISSUE THREAD

**Issue by geekgonecrazy** [boot2docker/osx-installer#100]
Running the latest version of OSX and latest boot2docker.

I've got a container with nginx / php-fpm serving up files.  In the development environment (boot2docker) i've got my local source code folder bound / mounted to the container.

All that's fine.  But i've got several js files that on being served are all truncated and funky.  As in like at the last line of the file it'll wrap and start outputting another file.  Other files it'll just chop off a random amount.

I've checked the actual files and they are fine.  I've also built the container putting the current files inside and ran it.  The files are fine.  So seems to be something with the mount...

Searched through the issues, didn't find any matching this.  New issue?  Known? Suggestions?

Thanks,

Aaron

**Comment by SvenDowideit** [comment]
@tianon @bfirsh ?

**Comment by shirk3y** [comment]
+1 The same issue here.

**Comment by shirk3y** [comment]
This can be related: https://forums.virtualbox.org/viewtopic.php?f=3&t=24905

**Comment by shirk3y** [comment]
Or this: https://github.com/noplay/docker-osx/issues/68

**Comment by shirk3y** [comment]
In fact, adding `sendfile off;` at location tag fixed it.

**Comment by abesto** [comment]
+1 same here. Confirming, `sendfile off` in the `location` section seems to fix the issue.

**Comment by geekgonecrazy** [comment]
That does the trick..  But why? When not mounting a volume it works.  

Interesting.

**Comment by yeliu84** [comment]
+1 `sendfile off` solved this issue, thank you all!

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
