### ISSUE TITLE
Docker throws error on latest boot2docker

### ISSUE THREAD

**Issue by sansb** [boot2docker/osx-installer#101]
Just downloaded and installed latest boot2docker from https://github.com/boot2docker/osx-installer/releases/tag/v1.5.0 and docker client is throwing this error-

    $ boot2docker version
        Boot2Docker-cli version: v1.5.0
        Git commit: ccd9032

    $ docker version
        Client version: 1.5.0
        Client API version: 1.17
        Go version (client): go1.4.1
        Git commit (client): a8a31ef
        OS/Arch (client): darwin/amd64
        FATA[0000] Error response from daemon: client and server don't have same version (client : 1.17, server: 1.15) 

edit: I'm running VirtualBox version 4.3.20 r96996

**Comment by acalub** [comment]
try rebooting your machine, that fixed for me. osx 10.10.1

**Comment by meskyanichi** [comment]
I've had the exact same issue just now. I did the following to resolve the issue. Note that I didn't have any important images so I simply dropped everything and started from scratch.

1. Open VirtualBox and remove all images. (note that this might not be necessary.)
2. `rm -rf ~/VirtualBox\ VMs`.
3. Install the latest version of VirtualBox.
4. Install the latest version of boot2docker.
5. `boot2docker init`.
6. `boot2docker start`.
7. `docker run hello-world`.

**Comment by ArnaudPiroelle** [comment]
Same issue for me.

You can use following command to upgrade boot2docker:
```
boot2docker upgrade
```

This download latest boot2docker iso and upgrade your VM.

**Comment by WangWenchao** [comment]
Today I met the client and server version not the same problem 
I download the Vbox latest version and boot2docker latest but get the bellow error ouput:
➜  ~  boot2docker start
Waiting for VM and Docker daemon to start...
..............................oooo
Started.
Writing /Users/kewin/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/kewin/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/kewin/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

➜  ~  docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
FATA[0000] Error response from daemon: client and server don't have same version (client : 1.17, server: 1.15)

is there any solution

**Comment by WangWenchao** [comment]
Today I met the client and server version not the same problem 
I download the Vbox latest version and boot2docker latest but get the bellow error ouput:
➜  ~  boot2docker start
Waiting for VM and Docker daemon to start...
..............................oooo
Started.
Writing /Users/kewin/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/kewin/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/kewin/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

➜  ~  docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
FATA[0000] Error response from daemon: client and server don't have same version (client : 1.17, server: 1.15)

is there any solution

**Comment by fpighi** [comment]
I had the same issue. `boot2docker upgrade` fixed it for me.

**Comment by allomov** [comment]
`boot2docker upgrade` worked for me.

**Comment by danielpassos** [comment]
`boot2docker upgrade` worked for me.

**Comment by sansb** [comment]
`boot2docker upgrade` worked for me as well. Closing issue.
