### ISSUE TITLE
Installer should not "upgrade" to an older version of VB

### ISSUE THREAD

**Issue by shawnbutts** [boot2docker/osx-installer#102]
I'm running VB 4.3.22 and the B2D 1.5.0 installer upgraded me to VB 4.3.20.  

At the least, this was unexpected.

**Comment by SvenDowideit** [comment]
yeah, i thought we protected against that too :/

**Comment by JeNeSuisPasDave** [comment]
That happened to me as well. But I upgraded VirtualBox to 4.3.26 (on OS X) and now "docker" commands won't connect to the VM. I suspect the issue is with Guest Additions, but I cannot figure out how to update them for the boot2docker VM.

I get:

```
FATA[0032] An error occurred trying to connect: Get https://192.168.59.104:2376/v1.17/containers/json?all=1: dial tcp 192.168.59.104:2376: i/o timeout
```
I can ssh into the VM just fine (using `boot2docker ssh`) and my environment variables are correct.

**Comment by JeNeSuisPasDave** [comment]
Hmmm. Rebooting OS X seemed to fix the docker client connectivity issue. So I'm now able to run with VB 4.3.26. I've no idea whether the VM has the Guest Addtions for 4.3.20 or 4.3.26, and I don't know how to check or how to upgrade the Guest Additions. But I'm able to share host files with a container (using the "-v" option of 'docker run'), so maybe updating the Guest Additions is not critical ... though it could be with some future release of VirtualBox.

**Comment by shawnbutts** [comment]
this is still an issue.

1.7.0 is want's to upgrade me to VB 4.3.28 which is what i have installed.

**Comment by therealcmj** [comment]
What's worse is that if you have 5.0 installed the installer blows it away without warning and installs 4.3.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
