### ISSUE TITLE
Failed to install caused that 'VirtualBox is still running'

### ISSUE THREAD

**Issue by kuno** [boot2docker/osx-installer#105]
I try to install boot2docker on my macbook.

I tried two ways, use the official package and through `homebrew cask`, both were failed. It said that `The installer has detected that VirtualBox is still running.` However, when I installing, I am pretty sure thare are no virtualbox vm running anywhere on my machine.

Here is my setup

```
os 10.10.2
boot2docker 1.5.0
virtualbox 4.3.24
```

**Comment by andreineculau** [comment]
try running `/bin/ps -e | /usr/bin/grep -E "VirtualBox.*startvm|VBoxNetDHCP|VBoxNetNAT|VBoxHeadless|VBoxSVC" | /usr/bin/grep -qv grep` and check the process list (that's what the installer runs internally)

PS: I noticed this behaviour due to boot2docker-status

**Comment by codeguy** [comment]
I am running into the same issue. I have confirmed VirtualBox is not running. I ran the command provided by @andreineculau and no results are shown. Still, boot2docker installer package fails with attached message.
![screen shot 2015-03-24 at 9 47 22 am](https://cloud.githubusercontent.com/assets/31677/6802958/cad4f9ee-d20a-11e4-97c3-511035f9d91f.png)

**Comment by codeguy** [comment]
When all else fails, reboot. That fixed the issue for me.

**Comment by onlydole** [comment]
boot2docker-status was the culprit for me...thanks!

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
