### ISSUE TITLE
Kernel Panic on Early 2015 Macbook Pro

### ISSUE THREAD

**Issue by caleblloyd** [boot2docker/osx-installer#106]
Using the new Early 2015 Macbook Pro (MacBookPro12,1).  "boot2docker init" works fine, however when starting using "boot2docker up" or the VirtualBox UI, I get a kernel panic.

VirtualBox Versions tested with problem: 4.3.24, 4.3.22, 4.3.20, all others untested
Boot2Docker Versions tested with problem: 1.50, 1.41, all others untested

The kernel extension referenced as the culprit in the kernel panic output is org.virtualbox.kext.VBoxDrv(4.3.24), so I have opened an upstream Virtualbox Ticket (kernel panic log is uploaded there): https://www.virtualbox.org/ticket/13951

Anyone know of a cause or workaround in the meantime?

**Comment by caleblloyd** [comment]
Workaround is to install Virtualbox 4.3.25 test build.  Hopefully this GA's soon and can be integrated in the next boot2docker OSX Launcher release.

**Comment by SvenDowideit** [comment]
@tianon

**Comment by Dangeranger** [comment]
Experiencing a similar problem here, link to Gist of panic crash report below. All crashes are based on the bundled VBoxManager (4.3.20) 
https://gist.github.com/Dangeranger/d5076fd104cd665fdb54

**Comment by kmadel** [comment]
Updated VBox to 4.3.27 - don't get kernel panic but ssh key set up no longer working and login is required:

..............docker@localhost's password:

**Comment by algobardo** [comment]
Same here, working if virtualbox is installed after (so that the kext are overriden).
However, what is the default password ?

**Comment by caleblloyd** [comment]
Pretty sure it's "tcuser" (https://github.com/boot2docker/boot2docker/blob/master/README.md)

**Comment by kmadel** [comment]
I updated to VBox 4.3.27 after doing the Mac OS X install but it appears there is an issue with the VirtualBox Guest Additions not being installed and this appears to be causing an issue with the init.  I get the following error on boot2docker -v init:
```
2015/03/30 12:44:29 executing: VBoxManage storageattach boot2docker-vm --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/kmadel/.boot2docker/boot2docker.iso
2015/03/30 12:44:29 executing: VBoxManage storageattach boot2docker-vm --storagectl SATA --port 1 --device 0 --type hdd --medium /Users/kmadel/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vmdk
VBoxManage: error: The medium '/Users/kmadel/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vmdk' can't be used as the requested device type
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Medium, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/Users/kmadel/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vmdk"
error in run: Failed to initialize machine "boot2docker-vm": exit status 1
```

**Comment by jerrymf** [comment]
Guys, I have (probably) workaround or you. I got same error as kmadel. There can't be spaces in path to VirtualBox machines! If you put the path without spaces and run 'boot2docker init' (and 'boot2docker delete' before if exists one), all will be inited well (using VB 4.3.27). Hope it helped.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
