### ISSUE TITLE
Install fails if VMWare is running

### ISSUE THREAD

**Issue by starksm64** [boot2docker/osx-installer#107]
I tried installing the Boot2Docker-1.5.0.pkg package and it fails when running the installation scripts:

tmp 1006]$ tail -40 /var/log/install.log 
        "PKLeopardPackage file://localhost/tmp/Boot2Docker-1.5.0.pkg#boot2dockeriso.pkg",
        "PKLeopardPackage file://localhost/tmp/Boot2Docker-1.5.0.pkg#boot2dockerapp.pkg",
        "PKLeopardPackage file://localhost/tmp/Boot2Docker-1.5.0.pkg#VBoxKEXTs.pkg",
        "PKLeopardPackage file://localhost/tmp/Boot2Docker-1.5.0.pkg#VirtualBox.pkg",
        "PKLeopardPackage file://localhost/tmp/Boot2Docker-1.5.0.pkg#VirtualBoxCLI.pkg"
    )
Mar 17 15:02:14 scotts-imac installd[4498]: PackageKit: Extracting file://localhost/tmp/Boot2Docker-1.5.0.pkg#docker.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox/Root, uid=0)
Mar 17 15:02:14 scotts-imac installd[4498]: PackageKit: Extracting file://localhost/tmp/Boot2Docker-1.5.0.pkg#boot2docker.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox/Root/usr/local/bin, uid=0)
Mar 17 15:02:14 scotts-imac installd[4498]: PackageKit: Extracting file://localhost/tmp/Boot2Docker-1.5.0.pkg#boot2dockeriso.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox/Root/usr/local/share/boot2docker, uid=0)
Mar 17 15:02:14 scotts-imac installd[4498]: PackageKit: Extracting file://localhost/tmp/Boot2Docker-1.5.0.pkg#boot2dockerapp.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox/Root/Applications, uid=0)
Mar 17 15:02:14 scotts-imac installd[4498]: PackageKit: Extracting file://localhost/tmp/Boot2Docker-1.5.0.pkg#VBoxKEXTs.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox/Root/Library/Application Support/VirtualBox, uid=0)
Mar 17 15:02:15 scotts-imac installd[4498]: PackageKit: Extracting file://localhost/tmp/Boot2Docker-1.5.0.pkg#VirtualBox.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox/Root/Applications, uid=0)
Mar 17 15:02:18 scotts-imac installd[4498]: PackageKit: Extracting file://localhost/tmp/Boot2Docker-1.5.0.pkg#VirtualBoxCLI.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox/Root/usr/bin, uid=0)
Mar 17 15:02:18 scotts-imac installd[4498]: PackageKit: prevent user idle system sleep
Mar 17 15:02:18 scotts-imac installd[4498]: PackageKit: suspending backupd
Mar 17 15:02:18 scotts-imac installd[4498]: PackageKit: Executing script "./preflight" in /private/tmp/PKInstallSandbox.LkNvaD/Scripts/org.virtualbox.pkg.virtualbox.FuEFaj
Mar 17 15:02:18 scotts-imac install_monitor[71624]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Mar 17 15:02:18 scotts-imac installd[4498]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/717B936B-201E-41DC-85C8-DBC1D5A6F00A.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox
Mar 17 15:02:18 scotts-imac installd[4498]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/717B936B-201E-41DC-85C8-DBC1D5A6F00A.activeSandbox/Root (3 items) to /
Mar 17 15:02:18 scotts-imac installd[4498]: PackageKit: Executing script "./postflight" in /private/tmp/PKInstallSandbox.LkNvaD/Scripts/org.virtualbox.pkg.vboxkexts.WcyXwu
Mar 17 15:02:18 scotts-imac installd[4498]: ./postflight: /Library/LaunchDaemons/org.virtualbox.startup.plist
Mar 17 15:02:19 scotts-imac installd[4498]: ./postflight: /Library/Application Support/VirtualBox/VBoxNetAdp.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
Mar 17 15:02:19 scotts-imac install_monitor[71624]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Mar 17 15:02:20 scotts-imac installd[4498]: PackageKit: releasing backupd
Mar 17 15:02:20 scotts-imac installd[4498]: PackageKit: allow user idle system sleep
Mar 17 15:02:20 scotts-imac installd[4498]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Boot2Docker-1.5.0.pkg”." UserInfo=0x7fed05b36bd0 {NSFilePath=./postflight, NSURL=file://localhost/tmp/Boot2Docker-1.5.0.pkg#VBoxKEXTs.pkg, PKInstallPackageIdentifier=org.virtualbox.pkg.vboxkexts, NSLocalizedDescription=An error occurred while running scripts from the package “Boot2Docker-1.5.0.pkg”.} {
        NSFilePath = "./postflight";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201cBoot2Docker-1.5.0.pkg\U201d.";
        NSURL = "file://localhost/tmp/Boot2Docker-1.5.0.pkg#VBoxKEXTs.pkg";
        PKInstallPackageIdentifier = "org.virtualbox.pkg.vboxkexts";
    }
Mar 17 15:02:20 scotts-imac Installer[71608]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Boot2Docker-1.5.0.pkg”." UserInfo=0x7ff921c43bc0 {NSFilePath=./postflight, NSURL=file://localhost/tmp/Boot2Docker-1.5.0.pkg#VBoxKEXTs.pkg, PKInstallPackageIdentifier=org.virtualbox.pkg.vboxkexts, NSLocalizedDescription=An error occurred while running scripts from the package “Boot2Docker-1.5.0.pkg”.}
Mar 17 15:02:20 scotts-imac installd[4498]: PackageKit: Running idle tasks
Mar 17 15:02:20 scotts-imac installd[4498]: PackageKit: Removing client PKInstallDaemonClient pid=71608, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Mar 17 15:02:20 scotts-imac installd[4498]: PackageKit: Done with sandbox removals
Mar 17 15:02:20 scotts-imac installd[4498]: PackageKit: Sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/3357A713-1E80-4F06-91C1-F1CFF1AC9AC2.sandbox: relevance 104
Mar 17 15:02:20 scotts-imac Installer[71608]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Mar 17 15:02:20 scotts-imac Installer[71608]: IFDInstallController 21C774F0 state = 8
Mar 17 15:02:20 scotts-imac Installer[71608]: Displaying 'Install Failed' UI.
Mar 17 15:02:20 scotts-imac Installer[71608]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

I have seen this conflict with libkern/kext before when I have had a vmware image running, and that turned out to be the case this time as well. When I shutdown the virtual machine, the install succeeds.
It would be good if a better error message about looking for running virtual machines was given, as well as a note in the install doc about this common problem.

**Comment by damnhandy** [comment]
This issue is present in boot2docker 1.7.1 as well. However, I am fairly confident that this is a VirtualBox issue and not a Boot2Docker issue. I have created this ticket here:

https://www.virtualbox.org/ticket/14281

The short version is that I ran into the same issue after bailing on the Boot2Docker installer and using the VirtualBox installer and got the same issue. I had to manually kill the background process in order to upgrade VBox.

__Workaround__
My workaround for upgrading boot2docker was to simply use the boot2docker command line tools:

    mbp:~ me$ boot2docker upgrade

This upgraded everything but VirtualBox. To get around the VBox issue, find the lingering `VBox` processes and kill them:

    mbp:~ me$ ps aux | grep VB
    me             1135   0.2  0.0  2451240   7088   ??  S     7:10AM   0:00.05 /Applications/VirtualBox.app/Contents/MacOS/VBoxXPCOMIPCD
    me             1137   0.2  0.1  2532164  11260   ??  S     7:10AM   0:00.13 /Applications/VirtualBox.app/Contents/MacOS/VBoxSVC --auto-shutdown
    me             1147   0.0  0.0  2450180    684 s000  S+    7:10AM   0:00.00 grep VB
    mbp:~ me$ kill -9 1137

Once you do that, the VBox installer will work. Hopefully Oracle will fix this someday.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
