### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wanghaisheng** [boot2docker/osx-installer#108]
OSX 10.10.2
boot2docker up 
when i run make ,the error is as follows

```
docker cp "build-osx-installer":/dmg/Docker.pkg .
2015/03/21 00:09:41 "Docker.pkg" is outside of "."
make: *** [dockerbuild] Error 1
```

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
