### ISSUE TITLE
boot2docker seems to not be working FATA[0000] error amongst other things.

### ISSUE THREAD

**Issue by ismael-rivera** [boot2docker/osx-installer#109]
New to docker. I need it for a project I'm working on but also just to learn. Please bare with me as I am a noob on this and have no idea what any of this means yet. 
I'm running on Mac OS X 10.6.8 Snow Leopard. 
FYI: I can't upgrade my OS so that is not an option for me right now.

So, I install boot2docker and when I go click on the icon I receive the following output:

```
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ bash
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ unset DYLD_LIBRARY_PATH ; unset LD_LIBRARY_PATH
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ mkdir -p ~/.boot2docker
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ if [ ! -f ~/.boot2docker/boot2docker.iso ]; then cp /usr/local/share/boot2docker/boot2docker.iso ~/.boot2docker/ ; fi
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ /usr/local/bin/boot2docker init 
/usr/local/bin/boot2docker up 
$(/usr/local/bin/boot2docker shellinit)
docker version
error in run: Failed to initialize machine "boot2docker-vm": exit status 1
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ /usr/local/bin/boot2docker up 
error in run: Failed to get machine "boot2docker-vm": machine does not exist (Did you run `boot2docker init`?)
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ $(/usr/local/bin/boot2docker shellinit)
error in run: Failed to get machine "boot2docker-vm": machine does not exist (Did you run `boot2docker init`?)
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
ismaelrivera@Ismael-Riveras-Mac-Pro-2:~$ 
```

What does this mean? How can I fix this? Thank You in advance.

**Comment by SydOps** [comment]
http://stackoverflow.com/questions/27815900/boot2docker-for-os-x-fails-to-start/27856327#27856327
http://stackoverflow.com/questions/29797420/my-boot2docker-installation-seems-to-not-be-working-what-am-i-doing-wrong

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
