### ISSUE TITLE
Why is /Users mounted?

### ISSUE THREAD

**Issue by herrernst** [boot2docker/osx-installer#111]
Hi,
I've installed boot2docker on OS X. I see that in the VBox image the whole /Users folder is shared and is mounted in the VM writeable:
`none on /Users type vboxsf (rw,nodev,relatime)`
I don't like the security implications that brings, you can even access other local OS X users' files from the VM. Can this not be reduced to a subfolder of my user directory?

**Comment by herrernst** [comment]
Okay, you can start boot2docker without sharing `/Users` this way:
`boot2docker start --vbox-share=disable`
Unfortunately, this cannot be set in a config.

**Comment by SvenDowideit** [comment]
@bfirsh can you please answer this?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
