### ISSUE TITLE
Running docker commands on osx can't connect to docker deamon on boot2docker-vm instance

### ISSUE THREAD

**Issue by talgiat** [boot2docker/osx-installer#112]
Still getting:

FATA[0032] An error occurred trying to connect: Get https://192.168.59.103:2376/v1.18/containers/json: dial tcp 192.168.59.103:2376: i/o timeout 

If I do fresh installation (that is remove completely boot2docker) things work, but after the computer goes to sleep I keep getting the error above when running any docker command from osx. 

I can still do boot2docker ssh and run docker commands on the boot2docker-vm instance, just not from osx outside virtual box.

Trying to shut down and restart the VM, running  $(boot2docker shellinit) or 
sudo route -nv add -net 192.168.59 -interface vboxnet0

still do not help, any ideas ?

**Comment by pdhar-tibco** [comment]
This happened when I just upgraded my virtual box independently outside docker. I removed virtual box and re-installed boot2docker 1.6.2 which comes with the latest virtual box. Same results.

**Comment by SvenDowideit** [comment]
yeah, its a general pain point of virtualbox. We're hoping to improve this with some major changes to the boot2docker iso in the 1.7 release, but no promises.

**Comment by jeanmartin** [comment]
Running 1.7.0, same issue :(

**Comment by damnhandy** [comment]
I've run into similar issues, what I have found is that the IP address changes. If you've set the `DOCKER_HOST` variable in your `.bash_profile`, make sure the IP address matches the return value from `boot2docker ip`. I am seeing the IP change each time I run `boot2docker delete` and then `boot2docker init`

**Comment by ankurtrivedi** [comment]
I am also running into the same issue. I was facing this issue when running docker commands "Get http:///var/run/docker.sock/v1.13/containers/json: dial unix /var/run/docker.sock: no such file or directory".

I followed this thread https://github.com/boot2docker/boot2docker/issues/392#issuecomment-61999567
and did the following:

boot2docker delete
In Virtualbox, go to VirtualBox (menu) => Preferences => Network => Host Only Networks
Delete the host only networks, then I re-added them
boot2docker init
boot2docker up

but then, I run into "Cannot connect to the Docker daemon. Is 'docker -d' running on this host?".

I am running Mac OSX Yosemite 10.10.2.

I have checked the IP from boot2docker ip is same as what I have exported as DOCKER_HOST.

Any ideas?

**Comment by bartekborek** [comment]
It's strange as the boot2docker image has an IP of 192.168.99.100 which you can ping from OS X and the ./docker/config..... json file specifies this as the IP address but it doesn't want to work. 

I was hoping to talk to it using terraform on the localhost but netstat shows no such port open on OS X.

Giving up and going to a native ubuntu environment to do the work I need to, shame as it would have been nice to work from within OS X. 

Hope someone fixes it....

**Comment by fuzzball5000** [comment]
+1 for a fix on this... it seems I have established connections to the Vbox machine, but nothing in the listening state for new connections. As others have commented, will have to switch to the 6 year old Elitebook+Ubuntu to do what I need to...

**Comment by rosscdh** [comment]
+1 this is a rather large problem on OSX

**Comment by rosscdh** [comment]
Actually seems to primarily being caused by a mismatch in clients

```
 docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64
Error response from daemon: client and server don't have same version (client API version: 1.20, server API version: 1.19)

```

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
