### ISSUE TITLE
`boot2docker init` downloads latest ISO, regardless of b2d version

### ISSUE THREAD

**Issue by carmstrong** [boot2docker/osx-installer#118]
I installed v1.6.2 of boot2docker and wanted to use that version, but it downloaded the latest ISO:

``` console
$  boot2docker up
error in run: Failed to get machine "boot2docker-vm": machine does not exist (Did you run `boot2docker init`?)
$  boot2docker init
Latest release for github.com/boot2docker/boot2docker is v1.7.0
Downloading boot2docker ISO image...
Success: downloaded https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso
    to /Users/carmstrong/.boot2docker/boot2docker.iso
Generating public/private rsa key pair.
Your identification has been saved in /Users/carmstrong/.ssh/id_boot2docker.
Your public key has been saved in /Users/carmstrong/.ssh/id_boot2docker.pub.
The key fingerprint is:
e0:af:c8:61:ea:76:ae:86:fa:1d:b8:43:5a:56:04:1f carmstrong@carmstrong-mbp.local
The key's randomart image is:
...
$ boot2docker version
Boot2Docker-cli version: v1.6.2
Git commit: cb2c3bc
```

**Comment by damnhandy** [comment]
Yeah, I ran into this too when trying to roll back to 1.6.2. Theoretically, you should be able to use `--iso-url` to specify the ISO you want. But I agree, boot2docker should get the ISO version for the version of boot2docker

**Comment by carmstrong** [comment]
> But I agree, boot2docker should get the ISO version for the version of boot2docker

:+1:

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
