### ISSUE TITLE
IP Address increments after subsequent calls to init

### ISSUE THREAD

**Issue by damnhandy** [boot2docker/osx-installer#120]
In trying work around other issues (re #112 and #119 ), I have had to reinitialize boot2docker by deleting it and rerunning init. However, each time I do this, the IP address increments. Here's what I am doing:

First, the certificates become invalid after a stop/start:

```
my-machine:$ docker images
An error occurred trying to connect: Get https://192.168.59.105:2376/v1.19/images/json: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.105
```

Note that the IP address is `192.168.59.105`. I stop boot2docker, delete the ISO, and rerun it:

```
my-machine:$ boot2docker stop
my-machine:$ boot2docker delete
my-machine:$ boot2docker init
my-machine:$ boot2docker start
Waiting for VM and Docker daemon to start...
.........................ooooooooooooooooooo
Started.
Writing /Users/me/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/me/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/me/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.106:2376
    export DOCKER_CERT_PATH=/Users/me/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1
```

Note that the IP address is now `192.168.59.106` instead of `192.168.59.105`. This was not the behavior in 1.6.x. It's annoying because my `.bash_profile` has the environment variables set already. I suspect that this is why folks are seeing the time out issue trying to connect to the docker daemon.

**Comment by danorton2** [comment]
I'm not certain of this workaround, but it has reset the IP address after these steps:
1. `boot2docker stop`
2. Manually delete the VM using the VirtualBox GUI, specifying "**Delete all files**".
3. Quit the VirtualBox GUI
4. `boot2docker init`
5. `boot2docker up`

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
