### ISSUE TITLE
Boot2Docker always downloads version 1.7

### ISSUE THREAD

**Issue by peggyl** [boot2docker/osx-installer#122]
Boot2Docker 1.6.0 and 1.5.0 both seem to be downloading the Boot2Docker 1.7.0 ISO image. Is this expected, or should the ISO image version match the OS X installer / boot2docker-cli version (as implied on [release notes](https://github.com/boot2docker/osx-installer/releases))?

This is on OS X 10.9.5 (Mavericks), with Go 1.4.2.

**Steps to reproduce:**
- Download and run Boot2Docker-1.6.0.pkg from [releases](https://github.com/boot2docker/osx-installer/releases). Also verified with 1.5.0, and may possibly be reproduced with other < 1.7.0 versions.
- Run `boot2docker init` or `boot2docker download`. Expected seems like it'd be 1.6.0 (same as OS X installer), but 1.7.0 is always downloaded.

There are issues later on where the client seems unable to connect to the daemon and boot2docker becomes unresponsive (to `info`, `stop`, `delete` commands). I'm not sure if this is the cause, but might it be related?

Note: I was trying to go back to 1.6.0 because of other issues running 1.7.0 (I'll revisit that).

**Output:**

```
$ boot2docker download
Latest release for boot2docker/boot2docker is v1.7.0
Downloading boot2docker ISO image...
Success: downloaded https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso
    to /Users/peggyli/.boot2docker/boot2docker.iso

$ boot2docker version
Boot2Docker-cli version: v1.5.0
Git commit: ccd9032
```

```
$ boot2docker start
Waiting for VM and Docker daemon to start...
.............................oooooooooooooooooo
Started.
Writing /Users/peggyli/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/peggyli/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/peggyli/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

$ boot2docker status
running

$ boot2docker version
Boot2Docker-cli version: v1.5.0
Git commit: ccd9032

$ boot2docker stop
error in run: Failed to stop machine "boot2docker-vm": exit status 1

$ boot2docker status
poweroff
```

**Comment by ingojaeckel** [comment]
I am noticing the same problem on 1.7.1. Google's Cloud SDK seems incompatible with Docker 1.7.1. I downgraded boot2docker to 1.7.0. But boot2docker download still grabs the 1.7.1 ISO file regardless. As a result I can't use the Cloud SDK against the last known working version 1.7.0. See [this discussion](https://groups.google.com/forum/#!topic/google-appengine/KRImkwB2owI) and [this bug](https://code.google.com/p/google-cloud-sdk/issues/detail?id=163) for details.

How can I specify which version of the ISO should be downloaded (instead of always downloading the most recent version)?

Thanks,
Ingo

**Comment by CleanCut** [comment]
+1

**Comment by amolomnie** [comment]
+1

**Comment by amolomnie** [comment]
Is there any workaround to make this work

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
