### ISSUE TITLE
Different style of boot2docker startup app

### ISSUE THREAD

**Issue by jakirkham** [boot2docker/osx-installer#124]
I made my own boot2docker startup app ( https://github.com/jakirkham/mac_boot2docker_startup_app ), which is similar to yours in terms of what it does. However, it doesn't open a terminal, but runs in the background. I would be willing to contribute it back if there was interest, but I would need some help understanding how the installer is being built.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
