### ISSUE TITLE
1.8.0 Release for Mac

### ISSUE THREAD

**Issue by onlydole** [boot2docker/osx-installer#125]
Hello @tianon! I wanted to know if the OS X installer will be ready soon for Mac distributions?

**Comment by onlydole** [comment]
@tianon, I did see the Docker Toolbox announcement...will that entirely replace the boot2docker solution?

**Comment by tianon** [comment]
That will, yes, however you can find 1.8.0 at https://github.com/boot2docker/osx-installer/releases/tag/v1.8.0.  You'll want to `boot2docker upgrade` after you install to make sure you get 1.8.1.

**Comment by tianon** [comment]
Docker Toolbox should install over the top of a boot2docker install properly, though.

**Comment by onlydole** [comment]
Thank you for all your help! The Toolbox setup will be much easier to use!
