### ISSUE TITLE
boot2docker OSX uninstall script tweak

### ISSUE THREAD

**Issue by TimZaman** [boot2docker/osx-installer#129]
Hi,

The boot2docker uninstall script for osx (uninstall.sh) tests for the existance of the command 'boot2docker' before it will uninstall boot2docker related things. This means that if this particular binary does not exist, it will not delete anything at all. If you had gotten rid of only the binary of the binary was not in your path at this particular moment, it also means the rest of the boot2docker files (which might exist!) are not removed. I would suggest removing the boot2docker test.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
