### ISSUE TITLE
Uninstall boot2docker on OSX El Capitan

### ISSUE THREAD

**Issue by wpc009** [boot2docker/osx-installer#130]
I try to uninstall boot2docker on OSX, using the shell script in this repo.
At end, it prints "All done". But after reboot. the `DOCKER_HOST` `DOCKER_TLS_VERIFY` still exists.
I cannot unset it.  These's no `~/.bash_profile`, `~/.bashrc` . I checked all the possible  location , still cannot find who set that env variable automatically.
How can I prevent these variables being set automatically?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
