### ISSUE TITLE
Uninstaller removes docker executable. WHY ?

### ISSUE THREAD

**Issue by oguzgelal** [boot2docker/osx-installer#131]
I wanted to get rid of boot2docker since it is deprecated and there is now `docker-machine`. So I ran the uninstaller script. I didn't realise this line:

``` bash
echo "Removing Docker executable..."
rm -f /usr/local/bin/docker
```

Why is docker executable being removed ?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
