### ISSUE TITLE
Installing boot2docker v1.3.2 on OS X EI Capitan (version: 10.11.4) fails

### ISSUE THREAD

**Issue by ganeshchand** [boot2docker/osx-installer#132]
Message from install.log
install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Boot2Docker-1.3.2.pkg”."

**Comment by ganeshchand** [comment]
Also, I noticed that the project boot2Docker OSX Installer has been suspended/deprecated.
Here's the note from https://github.com/boot2docker/osx-installer

> This project (the boot2docker OS X Installer) is officially deprecated in favor of the new Docker Toolbox.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
