### ISSUE TITLE
remove /usr/local/bin/docker only if this are a file, if link don't remove

### ISSUE THREAD

**Issue by vsth** [boot2docker/osx-installer#135]
Hi,
I have installed Docker for Mac https://docs.docker.com/engine/installation/mac/
With that we have `lrwxr-xr-x  1 user  staff  66 Nov 12 16:21 /usr/local/bin/docker -> /Users/thomas/Library/Group Containers/group.com.docker/bin/docker`
installed. I think boot2docker should remove /usr/local/bin/docker only if this is not a link.

**Comment by vsth** [comment]
https://github.com/boot2docker/osx-installer/pull/136

**Comment by yosifkit** [comment]
"Docker for Mac" does not use this installer.  This project was deprecated with https://github.com/boot2docker/osx-installer/pull/123.  You may want to open an issue on their repo: https://github.com/docker/for-mac.

**Comment by vsth** [comment]
Sure, but this installer removes the /usr/local/bin/docker from other docker implementations. I mean for me this issue are solved.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
