### ISSUE TITLE
Error Installing on Mac OS X 10.9.3 - No Error Message

### ISSUE THREAD

**Issue by motleydev** [boot2docker/osx-installer#27]
I tried running the installer but it says there is an error with installing. I see what looks like a truncated error message in the header where it trails with "You may want to try l" but then the message prints off the window and there's no way I can find to show it (scale the box, etc). I previously had docker installed via homebrew but tried to remove it (also using homebrew) - not sure if there's something related there. boot2docker installed fine.

**Comment by AmadeusK** [comment]
I solved this by booting in Safe Mode (hold SHIFT key while booting), uninstalling VirtualBox, rebooting (normally) and installing it again.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
