### ISSUE TITLE
v1.0.0 Crashes My Mac

### ISSUE THREAD

**Issue by benlwong** [boot2docker/osx-installer#30]
Running OSX 10.9.3.  Downloaded and installed v1.0.0 today fine.  But when I run boot2docker for the first time, it brought up my terminal, a bunch of messages flew by, and my system literally crashed.  I am not sure where the log file is, but more than happy to provide it if someone points me in the right direction.

I have never installed docker before today.

Thanks,
Ben

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
