### ISSUE TITLE
boot2docker fails after installation

### ISSUE THREAD

**Issue by josephschorr** [boot2docker/osx-installer#32]
Deleted old version of boot2docker (including VirtualBox) and installed version 1.0.0. After install, ran boot2docker init and got the following output:

2014/06/12 11:31:25 Creating VM boot2docker-vm...
2014/06/12 11:31:26 Apply interim patch to VM boot2docker-vm (https://www.virtualbox.org/ticket/12748)
2014/06/12 11:31:26 Setting NIC #1 to use NAT network...
2014/06/12 11:31:26 Port forwarding [ssh] tcp://127.0.0.1:2022 --> :22
2014/06/12 11:31:26 Port forwarding [docker] tcp://127.0.0.1:2375 --> :2375
2014/06/12 11:31:26 Failed to create host-only network interface: exit status 2

Trying to run the boot2docker image results in the following error being displayed in VirtualBox's preview window:

FATAL: Could not read from the boot medium! System halted.

**Comment by smarigowda** [comment]
I had the same issue and boot2docker -v init fixed it !

**Comment by arnfox** [comment]
venkat9099,
I have windows 10 and I'm bumping to the same issue. "VBoxManage.exe: error: Failed to create the host-only adapter"
Have you managed to get over this problem?

**Comment by sanjayhallan** [comment]
I am also having this problem on windows 10, any ideas?

**Comment by dsw88** [comment]
I'm also having this issue on Windows 10. Doing a delete and then a "boot2docker -v init" didn't seem to fix the problem.

The verbose output gives this error:
```
2015/08/04 12:30:21 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp
error in run: Failed to initialize machine "boot2docker-vm": exit status 1
```

**Comment by nijtmans** [comment]
Stumbled on exactly the same in Windows 10:

Boot2Docker-cli version: v1.7.1
Git commit: 8fdc6f5
2015/08/04 18:57:25 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/08/04 18:57:25 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/08/04 18:57:25 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list vms
2015/08/04 18:57:25 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --name boot2docker-vm --register
Virtual machine 'boot2docker-vm' is created and registered.
UUID: 856bed4b-1c48-49cc-b436-fd4fd5db4c9b
Settings file: 'C:\Users\Jan\VirtualBox VMs\boot2docker-vm\boot2docker-vm.vbox'
2015/08/04 18:57:25 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/08/04 18:57:25 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe setextradata boot2docker-vm VBoxInternal/CPUM/EnableHVP 1
2015/08/04 18:57:25 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm boot2docker-vm --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --natdnshostresolver1 off --natdnsproxy1 off --ostype Linux26_64 --cpus 2 --memory 2048 --vram 8 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --longmode on --hpet on --hwvirtex on --triplefaultreset off --nestedpaging on --largepages on --vtxvpid on --vtxux off --accelerate3d off --uart1 0x3F8 4 --uartmode1 server \\.\pipe\boot2docker-vm --boot1 dvd
2015/08/04 18:57:26 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/08/04 18:57:26 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm boot2docker-vm --nic1 nat --nictype1 virtio --cableconnected1 on
2015/08/04 18:57:26 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm boot2docker-vm --natpf1 ssh,tcp,127.0.0.1,2022,,22
2015/08/04 18:57:26 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
2015/08/04 18:57:26 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list dhcpservers
2015/08/04 18:57:27 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,int,int *)" at line 66 of file VBoxManageHostonly.cpp
error in run: Failed to initialize machine "boot2docker-vm": exit status 1

**Comment by dsw88** [comment]
It turns out this is a bug in VirtualBox with Windows 10, so it's not directly a boot2docker problem. This issue has the details: https://www.virtualbox.org/ticket/14040.

Their fix isn't released yet, but you can download a test build at https://www.virtualbox.org/download/testcase/VirtualBox-5.0.1-101902-Win.exe. That build installed and fixed things for me on Windows 10, allowing me to use boot2docker again.

**Comment by jsteffensen** [comment]
VirtualBox 5.0.1 fixed it on Win 10 for me. Thanks @dsw88
