### ISSUE TITLE
I'm getting timeouts.

### ISSUE THREAD

**Issue by clemens-tolboom** [boot2docker/osx-installer#37]
I get these all (most) of the time but the first run.

![Script timeout](https://cloud.githubusercontent.com/assets/371014/3413873/c8ffc682-fe0f-11e3-98c9-4fd7c9eb597f.png)

I guess this can be improved but not sure what's going on.

Is there a Applescript debug option?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
