### ISSUE TITLE
1.1.0 Install Failed on Mac OS X 10.9.3

### ISSUE THREAD

**Issue by varstr** [boot2docker/osx-installer#39]
Screenshot:
![screen shot 2014-07-07 at 3 45 26 pm](https://cloud.githubusercontent.com/assets/2390389/3492515/72860804-05ab-11e4-9318-181766a2e0fc.png)

Installer Log:

> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: LSExceptions [0x7f9902c14f90] loaded
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: @(#)PROGRAM:Install  PROJECT:Install-846
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: @(#)PROGRAM:Installer  PROJECT:Installer-721
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Hardware: MacBookPro10,2 @ 2.60 GHz (x 4), 8192 MB RAM
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Running OS Build: Mac OS X 10.9.3 (13D65)
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: TMPDIR=/var/folders/yg/x5j10jwd211bsp4mqv9p4wcr0000gn/T/
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: SHELL=/bin/zsh
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: HOME=/Users/iano
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: USER=iano
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: LOGNAME=iano
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: SSH_AUTH_SOCK=/tmp/launch-vofNXe/Listeners
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: Apple_PubSub_Socket_Render=/tmp/launch-xSvXUJ/Render
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: COMMAND_MODE=unix2003
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: __CHECKFIX1436934=1
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0:0
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Boot2Docker for Mac OS X 1.1.0 Installation Log
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Opened from: /Users/iano/Downloads/Boot2Docker-1.1.0.pkg
> Jul  7 15:46:38 ianos-MacBook-Pro.local Installer[10421]: Product archive /Users/iano/Downloads/Boot2Docker-1.1.0.pkg trustLevel=202
> Jul  7 15:46:39 ianos-MacBook-Pro.local Installer[10421]: JS: Hardware architecture detected: x86_64
> Jul  7 15:46:39 ianos-MacBook-Pro.local Installer[10421]: JS: OS version detected: 10.9.3
> Jul  7 15:46:40 ianos-MacBook-Pro.local Installer[10421]: JS: system.run /bin/sh .. returned: 1 result=true
> Jul  7 15:46:40 ianos-MacBook-Pro.local Installer[10421]: JS: result:true
> Jul  7 15:46:41 ianos-MacBook-Pro.local Installer[10421]: InstallerStatusNotifications plugin loaded
> Jul  7 15:46:47 ianos-MacBook-Pro.local runner[10428]: Administrator authorization granted.
> Jul  7 15:46:47 ianos-MacBook-Pro.local Installer[10421]: ================================================================================
> Jul  7 15:46:47 ianos-MacBook-Pro.local Installer[10421]: User picked Standard Install
> Jul  7 15:46:47 ianos-MacBook-Pro.local Installer[10421]: Choices selected for installation:
> Jul  7 15:46:47 ianos-MacBook-Pro.local Installer[10421]:   Upgrade: "Boot2Docker for Mac OS X"
> Jul  7 15:46:47 ianos-MacBook-Pro.local Installer[10421]:   Install: "Docker client for Mac OS X"
> Jul  7 15:46:47 ianos-MacBook-Pro.local Installer[10421]:       Boot2Docker-1.1.0.pkg#docker.pkg : io.docker.pkg.docker : 1.1.0
> Jul  7 15:46:47 ianos-MacBook-Pro.local Installer[10421]:   Install: "Boot2Docker management tool for Mac OS X"
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:       Boot2Docker-1.1.0.pkg#boot2docker.pkg : io.boot2docker.pkg.boot2docker : 1.1.0
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:   Install: "Boot2Docker ISO"
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:       Boot2Docker-1.1.0.pkg#boot2dockeriso.pkg : io.boot2dockeriso.pkg.boot2dockeriso : 1.1.0
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:   Install: "Boot2docker Quick-start applet for Mac OS X"
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:       Boot2Docker-1.1.0.pkg#boot2dockerapp.pkg : io.boot2docker.pkg.boot2dockerapp : 1.1.0
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:   Upgrade: "Oracle VM VirtualBox Kernel Extensions"
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:       Boot2Docker-1.1.0.pkg#VBoxKEXTs.pkg : org.virtualbox.pkg.vboxkexts : 4.3.8
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:   Upgrade: "Oracle VM VirtualBox"
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:       Boot2Docker-1.1.0.pkg#VirtualBox.pkg : org.virtualbox.pkg.virtualbox : 4.3.8
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:   Upgrade: "Oracle VM VirtualBox Command Line Utilities"
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]:       Boot2Docker-1.1.0.pkg#VirtualBoxCLI.pkg : org.virtualbox.pkg.virtualboxcli : 4.3.8
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: ================================================================================
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: It took 0.00 seconds to summarize the package selections.
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: -[IFDInstallController(Private) _buildInstallPlan]: location = file://localhost
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/iano/Downloads/Boot2Docker-1.1.0.pkg#docker.pkg
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/iano/Downloads/Boot2Docker-1.1.0.pkg#boot2docker.pkg
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/iano/Downloads/Boot2Docker-1.1.0.pkg#boot2dockeriso.pkg
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/iano/Downloads/Boot2Docker-1.1.0.pkg#boot2dockerapp.pkg
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/iano/Downloads/Boot2Docker-1.1.0.pkg#VBoxKEXTs.pkg
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/iano/Downloads/Boot2Docker-1.1.0.pkg#VirtualBox.pkg
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/iano/Downloads/Boot2Docker-1.1.0.pkg#VirtualBoxCLI.pkg
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: Set authorization level to root for session
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: Package file://localhost/Users/iano/Downloads/Boot2Docker-1.1.0.pkg#VirtualBoxCLI.pkg not supported by PK
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: Will use IF session
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: PFPackage::packageWithURL - can't instantiate package: /Users/iano/Downloads/Boot2Docker-1.1.0.pkg
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: Error opening package "Boot2Docker-1.1.0.pkg#VirtualBoxCLI.pkg".
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: Install failed: The Installer could not install the software because there was no software found to install.
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: IFDInstallController 2E5CD80 state = 8
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: Displaying 'Install Failed' UI.
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: 'Install Failed' UI displayed message:'The Installer could not install the software.  
>     The Installer could not install the software because there was no software found to install.'.
> Jul  7 15:46:48 ianos-MacBook-Pro.local Installer[10421]: LSExceptions [0x7f9902c14f90] unloaded

**Comment by beanlee** [comment]
the same to varstr, Thx! : )
Re download the pkg file solve this problem.
