### ISSUE TITLE
[UX] installation - new Summary screen for Docker Hub (optional) registration

### ISSUE THREAD

**Issue by j0hnst0n** [boot2docker/osx-installer#54]
Additional context: https://trello.com/c/O0hxnGCq

A new screen between "Installing" (Image A) and "Summary" (Image B) screens
- The screen headline is: "Sign-up for a free Docker Hub account"
- The subhead is:  "Save and share container images, automate workflows, and more."
- Then this form: https://hub.docker.com/account/signup/
- ...but with updated per https://github.com/docker/docker-io/issues/713 (we want to keep GH option as well)
- The form has three buttons:<br>
  *\* Go back (as do all installer forms)<br>
  *\* Sign-up: which submits form just like https://hub.docker.com/account/signup/<br>
  *\* Skip: which skips Hub registration and moves user to Summary screen

Image A
![image](https://cloud.githubusercontent.com/assets/1610391/3851354/56836920-1e93-11e4-90e5-8b30d44e67b6.png)

Image B
![image](https://cloud.githubusercontent.com/assets/1610391/3851360/6833cb24-1e93-11e4-9ece-557bf9c38652.png)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
