### ISSUE TITLE
iTerm support

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/osx-installer#62]
@artiom can you please make a new PR with the changes from #61, and then add more to the iTerm detection so that we don't trigger any UI if iTerm is not installed?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
