### ISSUE TITLE
V1.2 'Upgrade' failed to in saved boot2docker host

### ISSUE THREAD

**Issue by ccp999** [boot2docker/osx-installer#63]
Hi,

I just tried the v1.2 installer to use 'boot2docker upgrade' after a 'boot2docker save'.
and once done with no error msg.   It seems 'boot2docker upgrade' cannot docker server from 1.13 to 1.14.

iTags-MacBook-Pro:~ ccp999$ boot2docker up
Waiting for VM and Docker daemon to start...
......
Started.
Your DOCKER_HOST env variable is already set correctly.

iTags-MacBook-Pro:~ ccp999$ docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): darwin/amd64
2014/08/23 18:43:28 Error response from daemon: client and server don't have same version (client : 1.14, server: 1.13)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
