### ISSUE TITLE
Boot2Docker 1.2.0 on Mac OSX 10.9.4 generates bsdthread_register error

### ISSUE THREAD

**Issue by suriyanto** [boot2docker/osx-installer#67]
I have just installed Boot2Docker 1.2.0 on Mac OSX 10.9.4. When I run any boot2docker command, I get this error:

fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x522c75)
    /usr/src/go/src/pkg/runtime/panic.c:520 +0x69
runtime.goenvs()
    /usr/src/go/src/pkg/runtime/os_darwin.c:88 +0x62
runtime.schedinit()
    /usr/src/go/src/pkg/runtime/proc.c:164 +0x76
_rt0_go()
    /usr/src/go/src/pkg/runtime/asm_amd64.s:91 +0x114

I also tried using Boot2Docker 1.1.2 with the same problem.

I finally installed it using Homebrew and everything is working. I can help reproduce if there is any interest into looking into this.

Thanks,
Suriyanto

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
