### ISSUE TITLE
shouldn't the docs use `boot2docker shellinit`?

### ISSUE THREAD

**Issue by hangtwenty** [boot2docker/osx-installer#68]
Shouldn't the documentation at http://docs.docker.com/installation/mac/ recommend using `$(boot2docker shellinit)` instead of `export DOCKER_HOST=tcp://$(boot2docker ip 2>/dev/null):2375` ? 

I saw this substitution recommended [here](https://github.com/boot2docker/boot2docker/issues/392) by @SvenDowideit and it makes sense to me

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
