### ISSUE TITLE
boot2docker up really slow

### ISSUE THREAD

**Issue by Globegitter** [boot2docker/osx-installer#69]
In the Video that shows the Mac OSX installation boot2docker up just taks a few seconds, for me it takes quite a long time and is slower than booting an Ubuntu VM:
![screen shot 2014-09-20 at 23 31 57](https://cloud.githubusercontent.com/assets/2580254/4346827/c2beddfc-4118-11e4-90bd-a823e9f88170.png)

I tried installing it via homebrew as well as via this installer and both seem to have equal times. Any reasons why this could be so slow?

**Comment by VolkerH** [comment]
I also have the problem with really slow startup. I installed boot2docker on OS X 10.8.5 on a 2012 Macbook Pro Retina and am seemingly waiting forever on first boot. 

    Waiting for VM and Docker daemon to start...
    ..........................................................................ooooo

I tried with both version 1.3.2 and 1.4.1 of boot2docker but have been giving up after 20 minutes or so of waiting.

**Comment by SvenDowideit** [comment]
@VolkerH I would suggest using the vurtual box GUI to stop the vm, and then start it using the GUI - so that you can see the bootup output. This may tell you more.

**Comment by krrg** [comment]
@theRemix  Completely removing the whole VM worked for me as well.

**Comment by mcrowson** [comment]
I am having the same issue. Took 15-30 seconds to launch for the first time (on 2014 Mac with loads of hardware). Subsequent launches are crawling. I initially got boot2docker from brew cask. I tried doing the image removal and reinitializing as suggested, but continued to see the same thing. I removed boot2docker from brew and then downloaded the package and tried the installer. Just ran the boot2docker from my Applications and it is still taking a long time (running on 5 minutes now).

**Comment by mcrowson** [comment]
Waiting for VM and Docker daemon to start...
..........................................................................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
Started.
  Trying to get Docker socket one more time
Error requesting socket: exit status 255
Auto detection of the VM's Docker socket failed.
Please run `boot2docker -v up` to diagnose.


real	1020m13.457s
user	0m0.290s
sys	0m0.324s

**Comment by mcrowson** [comment]
boot2docker -v init
Boot2Docker-cli version: v1.6.2
Git commit: cb2c3bc
2015/05/21 09:34:02 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/05/21 09:34:02 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/05/21 09:34:02 executing: VBoxManage list vms
2015/05/21 09:34:02 executing: VBoxManage createvm --name boot2docker-vm --register
Virtual machine 'boot2docker-vm' is created and registered.
UUID: 56ca0c0f-e700-4331-bfec-b91abc4b0933
Settings file: '/Users/matthewcrowson/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox'
2015/05/21 09:34:02 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/05/21 09:34:02 executing: VBoxManage setextradata boot2docker-vm VBoxInternal/CPUM/EnableHVP 1
2015/05/21 09:34:02 executing: VBoxManage modifyvm boot2docker-vm --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --natdnshostresolver1 off --natdnsproxy1 off --ostype Linux26_64 --cpus 4 --memory 2048 --vram 8 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --longmode on --synthcpu off --hpet on --hwvirtex on --triplefaultreset off --nestedpaging on --largepages on --vtxvpid on --vtxux off --accelerate3d off --uart1 0x3F8 4 --uartmode1 server /Users/matthewcrowson/.boot2docker/boot2docker-vm.sock --boot1 dvd
2015/05/21 09:34:02 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/05/21 09:34:02 executing: VBoxManage modifyvm boot2docker-vm --nic1 nat --nictype1 virtio --cableconnected1 on
2015/05/21 09:34:02 executing: VBoxManage controlvm boot2docker-vm natpf1 ssh,tcp,127.0.0.1,2022,,22
2015/05/21 09:34:02 executing: VBoxManage list hostonlyifs
2015/05/21 09:34:02 executing: VBoxManage list dhcpservers
2015/05/21 09:34:02 executing: VBoxManage modifyvm boot2docker-vm --nic2 hostonly --nictype2 virtio --cableconnected2 on --hostonlyadapter2 vboxnet0
2015/05/21 09:34:02 executing: VBoxManage storagectl boot2docker-vm --name SATA --add sata --portcount 4 --hostiocache on --bootable on
2015/05/21 09:34:02 executing: VBoxManage storageattach boot2docker-vm --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/matthewcrowson/.boot2docker/boot2docker.iso
VBoxManage: error: The medium '/Users/matthewcrowson/.boot2docker/boot2docker.iso' can't be used as the requested device type
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Medium, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/Users/matthewcrowson/.boot2docker/boot2docker.iso"
error in run: Failed to initialize machine "boot2docker-vm": exit status 1


I ended up removing the iso and letting the init redownload it.
sudo rm -r ~/.boot2docker
boot2docker init

I wonder if the 'brew remove boot2docker' command didn't remove the ~/.boot2docker folder.

**Comment by maxfrigge** [comment]
No one really says what the desired startup time should be. I know this might vary depending on hardware but it would still be nice to get and idea if a 30s startup is considered fast or slow. I personally think it's quite slow for a Linux box. My Windows 10 VM boots faster than that. 

I have also noticed that startup times are very similar on my 2010 Macbook Pro (SSD) compared to a quad core with raid-0 SSDs.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
