### ISSUE TITLE
Getting the right date/time in the container

### ISSUE THREAD

**Issue by jkleiser** [boot2docker/osx-installer#72]
I have not yet figured out how to get the right date/time when running the container. Is this a problem specific to Mac OSX (running this boot2docker), or is it a general Docker problem?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
