### ISSUE TITLE
Upgrade to 1.3 fails

### ISSUE THREAD

**Issue by memelet** [boot2docker/osx-installer#81]
This seems the be very similar to the issue I had upgrading to 1.2. 

After installing the 1.3 dmg and starting I get

`2014/10/22 08:20:01 Error response from daemon: client and server don't have same version (client : 1.15, server: 1.14)`

Not sure if "client" means the .iso. So I deleted the existing .iso and then tried to run boot2docker download and get

`[2014-10-22 08:22:21] Could not get lastest release name! Cannot download boot2docker.iso.`

Last time I had to search around the disk and delete all traces of boot2docker and reinstall. I guess I will try that again.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
