### ISSUE TITLE
Running v1.1.2 pkg does not download 1.1.2 ISO

### ISSUE THREAD

**Issue by didip** [boot2docker/osx-installer#83]
I downloaded this version: https://github.com/boot2docker/osx-installer/releases/tag/v1.1.2, but boot2docker still downloads 1.3.0 ISO.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
