### ISSUE TITLE
boot2docker upgrade - server misbehaving

### ISSUE THREAD

**Issue by gabeki** [boot2docker/osx-installer#86]
$ boot2docker upgrade
error in run: Failed to get latest release: Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp: lookup api.github.com on [75.75.76.76]:53: server misbehaving

$ boot2docker version
Boot2Docker-cli version: v1.3.0
Git commit: deafc19

**Comment by goleksiak** [comment]
I'm getting this now too. I have the latest Docker 1.8.1

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
