### ISSUE TITLE
An error of type -10827 has occurred

### ISSUE THREAD

**Issue by stephenlawrence** [boot2docker/osx-installer#87]
I am receiving this message when I try to run the OS X docker app:

An error of type -10827 has occurred (Edit or OK)

I have updated to 1.3.1 but the error remains.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
