### ISSUE TITLE
uninstaller doesn't remove app

### ISSUE THREAD

**Issue by niltz** [boot2docker/osx-installer#88]
The uninstaller doesn't delete the boot2docker.app. Also, I'm not sure about this, but instead of removing the read receipts directly it might(?) be safer to use the pkgutil command to forget the packages if it exists.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
