### ISSUE TITLE
boot2docker taking long to start

### ISSUE THREAD

**Issue by ygrange** [boot2docker/osx-installer#90]
Hi,

I just downloaded Docker for my osx system (OSX 10.8.5). When I either start the boot2docker by clicking the app icon or through command line, the system waits a long time (75 minutes and counting. I now finally have the patience to wait for it) at this stage:
Grange@macgrange:~$ /usr/local/bin/boot2docker up 
Waiting for VM and Docker daemon to start...
..........................................................................ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

(so after it ran out of dots, it started counting with o signs...)

I have the impression that this is not really intended behaviour. Is there any way to improve the run time?

(EDIT: just updated the time it was running...)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
