### ISSUE TITLE
Question: How to upgrade my OSX client (not server)

### ISSUE THREAD

**Issue by PikachuEXE** [boot2docker/osx-installer#92]
I have already upgraded my boot2docker VM ISO
Just don't know how to upgrade my client

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
