### ISSUE TITLE
Installer not updated yet?

### ISSUE THREAD

**Issue by virtuald** [boot2docker/osx-installer#93]
I note that the boot2docker iso has been upgraded to 1.4.0, but the installer hasn't yet?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
