### ISSUE TITLE
VM creation fails on OSX 10.8.5

### ISSUE THREAD

**Issue by yscumc** [boot2docker/osx-installer#96]
I installed `Boot2Docker-1.4.1.pkg` on OSX 10.8.5 and afterwards opened `Applications/boot2docker.app`. After the SSH key was generated, I see the following error:

```
error in run: Failed to initialize machine "boot2docker-vm": exit status 2
bash-3.2$ /usr/local/bin/boot2docker up 
Waiting for VM and Docker daemon to start...
..........................................................................ooooo
```

`~/VirtualBox VMs/boot2docker-vm/Logs/VBox.log` shows that the VM was hung because there's no harddisk connected. Sure enough, in `~/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox`, under `<MediaRegistry>`, I see `<HardDisks/>` and `<DVDImages/>`, confirming there's no bootable media mounted.

What fixed it (hit ctrl-c to stop the waiting and typed it into the same terminal):

```
boot2docker poweroff
boot2docker delete
boot2docker init
boot2docker start
```

This seems similar to the issue at https://github.com/boot2docker/boot2docker-cli/issues/148 but I don't think it's anything to do with `DYLD_LIBRARY_PATH`

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
